
package br.edu.ifms.noticiaCliente.cliente;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "SEINoticia", targetNamespace = "http://servico.aula04.ifms.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SEINoticia {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "adicionar", targetNamespace = "http://servico.aula04.ifms.edu.br/", className = "br.edu.ifms.noticiaCliente.cliente.Adicionar")
    @ResponseWrapper(localName = "adicionarResponse", targetNamespace = "http://servico.aula04.ifms.edu.br/", className = "br.edu.ifms.noticiaCliente.cliente.AdicionarResponse")
    @Action(input = "http://servico.aula04.ifms.edu.br/SEINoticia/adicionarRequest", output = "http://servico.aula04.ifms.edu.br/SEINoticia/adicionarResponse")
    public boolean adicionar(
        @WebParam(name = "arg0", targetNamespace = "")
        Noticia arg0);

}
