
package br.edu.ifms.noticiaCliente.cliente;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "SEINoticia", targetNamespace = "http://servico.aula04.ifms.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SEINoticia {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "adicionar", targetNamespace = "http://servico.aula04.ifms.edu.br/", className = "br.edu.ifms.noticiaCliente.cliente.Adicionar")
    @ResponseWrapper(localName = "adicionarResponse", targetNamespace = "http://servico.aula04.ifms.edu.br/", className = "br.edu.ifms.noticiaCliente.cliente.AdicionarResponse")
    @Action(input = "http://servico.aula04.ifms.edu.br/SEINoticia/adicionarRequest", output = "http://servico.aula04.ifms.edu.br/SEINoticia/adicionarResponse")
    public boolean adicionar(
        @WebParam(name = "arg0", targetNamespace = "")
        Noticia arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "apagar", targetNamespace = "http://servico.aula04.ifms.edu.br/", className = "br.edu.ifms.noticiaCliente.cliente.Apagar")
    @ResponseWrapper(localName = "apagarResponse", targetNamespace = "http://servico.aula04.ifms.edu.br/", className = "br.edu.ifms.noticiaCliente.cliente.ApagarResponse")
    @Action(input = "http://servico.aula04.ifms.edu.br/SEINoticia/apagarRequest", output = "http://servico.aula04.ifms.edu.br/SEINoticia/apagarResponse")
    public boolean apagar(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @return
     *     returns java.util.List<br.edu.ifms.noticiaCliente.cliente.Noticia>
     */
    @WebMethod(operationName = "Listar")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Listar", targetNamespace = "http://servico.aula04.ifms.edu.br/", className = "br.edu.ifms.noticiaCliente.cliente.Listar")
    @ResponseWrapper(localName = "ListarResponse", targetNamespace = "http://servico.aula04.ifms.edu.br/", className = "br.edu.ifms.noticiaCliente.cliente.ListarResponse")
    @Action(input = "http://servico.aula04.ifms.edu.br/SEINoticia/ListarRequest", output = "http://servico.aula04.ifms.edu.br/SEINoticia/ListarResponse")
    public List<Noticia> listar();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "alterar", targetNamespace = "http://servico.aula04.ifms.edu.br/", className = "br.edu.ifms.noticiaCliente.cliente.Alterar")
    @ResponseWrapper(localName = "alterarResponse", targetNamespace = "http://servico.aula04.ifms.edu.br/", className = "br.edu.ifms.noticiaCliente.cliente.AlterarResponse")
    @Action(input = "http://servico.aula04.ifms.edu.br/SEINoticia/alterarRequest", output = "http://servico.aula04.ifms.edu.br/SEINoticia/alterarResponse")
    public boolean alterar(
        @WebParam(name = "arg0", targetNamespace = "")
        Noticia arg0);

}
