
package br.edu.ifms.noticiaCliente.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "SIBNoticiaService", targetNamespace = "http://servico.aula04.ifms.edu.br/", wsdlLocation = "http://localhost:8089/noticias?wsdl")
public class SIBNoticiaService
    extends Service
{

    private final static URL SIBNOTICIASERVICE_WSDL_LOCATION;
    private final static WebServiceException SIBNOTICIASERVICE_EXCEPTION;
    private final static QName SIBNOTICIASERVICE_QNAME = new QName("http://servico.aula04.ifms.edu.br/", "SIBNoticiaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8089/noticias?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIBNOTICIASERVICE_WSDL_LOCATION = url;
        SIBNOTICIASERVICE_EXCEPTION = e;
    }

    public SIBNoticiaService() {
        super(__getWsdlLocation(), SIBNOTICIASERVICE_QNAME);
    }

    public SIBNoticiaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIBNOTICIASERVICE_QNAME, features);
    }

    public SIBNoticiaService(URL wsdlLocation) {
        super(wsdlLocation, SIBNOTICIASERVICE_QNAME);
    }

    public SIBNoticiaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIBNOTICIASERVICE_QNAME, features);
    }

    public SIBNoticiaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIBNoticiaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SEINoticia
     */
    @WebEndpoint(name = "SIBNoticiaPort")
    public SEINoticia getSIBNoticiaPort() {
        return super.getPort(new QName("http://servico.aula04.ifms.edu.br/", "SIBNoticiaPort"), SEINoticia.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SEINoticia
     */
    @WebEndpoint(name = "SIBNoticiaPort")
    public SEINoticia getSIBNoticiaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servico.aula04.ifms.edu.br/", "SIBNoticiaPort"), SEINoticia.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIBNOTICIASERVICE_EXCEPTION!= null) {
            throw SIBNOTICIASERVICE_EXCEPTION;
        }
        return SIBNOTICIASERVICE_WSDL_LOCATION;
    }

}
