
package br.edu.ifms.calculadoraConsumidor;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Calculadora", targetNamespace = "http://servico.calculadora.ifms.edu.br/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Calculadora {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servico.calculadora.ifms.edu.br/Calculadora/subtrairRequest", output = "http://servico.calculadora.ifms.edu.br/Calculadora/subtrairResponse")
    public double subtrair(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0,
        @WebParam(name = "arg1", partName = "arg1")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servico.calculadora.ifms.edu.br/Calculadora/multiplicarRequest", output = "http://servico.calculadora.ifms.edu.br/Calculadora/multiplicarResponse")
    public double multiplicar(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0,
        @WebParam(name = "arg1", partName = "arg1")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servico.calculadora.ifms.edu.br/Calculadora/somarRequest", output = "http://servico.calculadora.ifms.edu.br/Calculadora/somarResponse")
    public double somar(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0,
        @WebParam(name = "arg1", partName = "arg1")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servico.calculadora.ifms.edu.br/Calculadora/dividirRequest", output = "http://servico.calculadora.ifms.edu.br/Calculadora/dividirResponse")
    public double dividir(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0,
        @WebParam(name = "arg1", partName = "arg1")
        double arg1);

}
