
package br.edu.ifms.calculadoraConsumidor;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "CalculadoraImplService", targetNamespace = "http://servico.calculadora.ifms.edu.br/", wsdlLocation = "http://localhost:8085/servico/calculadora?wsdl")
public class CalculadoraImplService
    extends Service
{

    private final static URL CALCULADORAIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULADORAIMPLSERVICE_EXCEPTION;
    private final static QName CALCULADORAIMPLSERVICE_QNAME = new QName("http://servico.calculadora.ifms.edu.br/", "CalculadoraImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/servico/calculadora?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULADORAIMPLSERVICE_WSDL_LOCATION = url;
        CALCULADORAIMPLSERVICE_EXCEPTION = e;
    }

    public CalculadoraImplService() {
        super(__getWsdlLocation(), CALCULADORAIMPLSERVICE_QNAME);
    }

    public CalculadoraImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULADORAIMPLSERVICE_QNAME, features);
    }

    public CalculadoraImplService(URL wsdlLocation) {
        super(wsdlLocation, CALCULADORAIMPLSERVICE_QNAME);
    }

    public CalculadoraImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULADORAIMPLSERVICE_QNAME, features);
    }

    public CalculadoraImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculadoraImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Calculadora
     */
    @WebEndpoint(name = "CalculadoraImplPort")
    public Calculadora getCalculadoraImplPort() {
        return super.getPort(new QName("http://servico.calculadora.ifms.edu.br/", "CalculadoraImplPort"), Calculadora.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Calculadora
     */
    @WebEndpoint(name = "CalculadoraImplPort")
    public Calculadora getCalculadoraImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servico.calculadora.ifms.edu.br/", "CalculadoraImplPort"), Calculadora.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULADORAIMPLSERVICE_EXCEPTION!= null) {
            throw CALCULADORAIMPLSERVICE_EXCEPTION;
        }
        return CALCULADORAIMPLSERVICE_WSDL_LOCATION;
    }

}
