
package br.edu.ifms.servico;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "BoaNoiteImplService", targetNamespace = "http://servico.aula01.ifms.edu.br/", wsdlLocation = "http://localhost:8085/servico/cumprimento?wsdl")
public class BoaNoiteImplService
    extends Service
{

    private final static URL BOANOITEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOANOITEIMPLSERVICE_EXCEPTION;
    private final static QName BOANOITEIMPLSERVICE_QNAME = new QName("http://servico.aula01.ifms.edu.br/", "BoaNoiteImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/servico/cumprimento?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOANOITEIMPLSERVICE_WSDL_LOCATION = url;
        BOANOITEIMPLSERVICE_EXCEPTION = e;
    }

    public BoaNoiteImplService() {
        super(__getWsdlLocation(), BOANOITEIMPLSERVICE_QNAME);
    }

    public BoaNoiteImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOANOITEIMPLSERVICE_QNAME, features);
    }

    public BoaNoiteImplService(URL wsdlLocation) {
        super(wsdlLocation, BOANOITEIMPLSERVICE_QNAME);
    }

    public BoaNoiteImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOANOITEIMPLSERVICE_QNAME, features);
    }

    public BoaNoiteImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BoaNoiteImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BoaNoite
     */
    @WebEndpoint(name = "BoaNoiteImplPort")
    public BoaNoite getBoaNoiteImplPort() {
        return super.getPort(new QName("http://servico.aula01.ifms.edu.br/", "BoaNoiteImplPort"), BoaNoite.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BoaNoite
     */
    @WebEndpoint(name = "BoaNoiteImplPort")
    public BoaNoite getBoaNoiteImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servico.aula01.ifms.edu.br/", "BoaNoiteImplPort"), BoaNoite.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOANOITEIMPLSERVICE_EXCEPTION!= null) {
            throw BOANOITEIMPLSERVICE_EXCEPTION;
        }
        return BOANOITEIMPLSERVICE_WSDL_LOCATION;
    }

}
