
package br.edu.ifms.servico;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BoaNoite", targetNamespace = "http://servico.aula01.ifms.edu.br/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface BoaNoite {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servico.aula01.ifms.edu.br/BoaNoite/digaBoaNoiteRequest", output = "http://servico.aula01.ifms.edu.br/BoaNoite/digaBoaNoiteResponse")
    public String digaBoaNoite(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
